### ISSUE TITLE
npm package missing its sourcemaps

### ISSUE THREAD

**Issue by aleclarson** [Rich-Harris/sourcemap-codec#73]
`dist/sourcemap-codec.umd.js` has `//# sourceMappingURL=sourcemap-codec.umd.js.map` at the bottom, but the sourcemap file is not included.

**Comment by DarthVanger** [comment]
The same with `sourcemap-codec.es.js` - it has `//# sourceMappingURL=sourcemap-codec.es.js.map` in the bottom.

I'm getting this error during the build of `react-styleguidist` docs website
```
(Emitted value instead of an instance of Error) Cannot find SourceMap 'sourcemap-codec.es.js.map': Error: Can't resolve './sourcemap-codec.es.js.map' in '/[...]/node_modules/sourcemap-codec/dist'
./node_modules/buble/dist/buble-browser.es.js
263:9-19 "export 'default' (imported as 'require$$0') was not found in 'acorn'
./node_modules/buble/dist/buble-browser.es.js
264:17-27 "export 'default' (imported as 'require$$0') was not found in 'acorn'
[...]
```

Not sure how to reproduce this yet, getting this error only on CI server, but not locally.

But the sourcemaps are obviously missing :)

**Comment by Nols1000** [comment]
@Rich-Harris Any progress on this?
